<?php

/**
 * PHP version 5.6
 *
 * @package   Manifest
 * @author    Config Generator <mega@dev.logics.net.au>
 * @copyright 2013-2016 Vladimir Bashkirtsev
 * @license   https://opensource.org/licenses/MIT MIT License
 * @version   SVN: $Date$ $Revision$
 * @link      $HeadURL$
 */

/**
 * Automatically generated file, do not modify
 *
 * @donottranslate
 */

define("GENGO_EXCEPTION_NO_API_KEY", 1);
define("GENGO_EXCEPTION_NO_PRIVATE_KEY", 2);
define("GENGO_EXCEPTION_NO_RESPONSE_AVAILABLE_YET", 3);
define("GENGO_EXCEPTION_ID_IS_NOT_SET", 4);
define("GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_RATING", 5);
define("GENGO_EXCEPTION_JOB_MUST_CONTAIN_VALID_REASON", 6);
define("GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_FOLLOWUP", 7);
define("GENGO_EXCEPTION_REASON_REQUIRED", 8);
define("GENGO_EXCEPTION_INVALID_RESPONSE_FORMAT", 9);
define("GENGO_EXCEPTION_INVALID_API_KEY", 10);
define("GENGO_EXCEPTION_INVALID_PRIVATE_KEY", 11);
define("GENGO_EXCEPTION_INVALID_JOB_ID", 12);
define("GENGO_EXCEPTION_INVALID_REVISION_ID", 13);
define("GENGO_EXCEPTION_COMMENT_REQUIRED", 14);
define("GENGO_EXCEPTION_VALID_PARAMETER_IS_REQUIRED", 15);
define("GENGO_EXCEPTION_URL_ATTACHMENTS_NOT_ARRAY", 16);
define("GENGO_EXCEPTION_URL_ATTACHMENT_IS_NOT_HTTP_URL", 17);
define("GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_FILENAME", 18);
define("GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_MIMETYPE", 19);
define("GENGO_EXCEPTION_MUST_CONTAIN_VALID_STATUS", 20);
define("GENGO_EXCEPTION_TIMESTAMP_MUST_BE_VALID", 21);
define("GENGO_EXCEPTION_COUNT_MUST_MUST_BE_VALID", 22);
define("GENGO_EXCEPTION_JOB_ID_REQUIRED", 23);
define("GENGO_EXCEPTION_INVALID_JOB_ID_SUPPLIED", 24);
define("GENGO_EXCEPTION_MUST_CONTAIN_VALID_BODY", 25);
define("GENGO_EXCEPTION_JOB_MISSING_FILE_KEY", 26);
define("GENGO_EXCEPTION_IS_NOT_VALID_FILE_KEY", 27);
define("GENGO_EXCEPTION_FILE_KEY_MISSING", 28);
define("GENGO_EXCEPTION_COULD_NOT_FIND_FILE", 29);
define("EXCEPTION_CANNOT_RUN_TESSERACT", 30);
define("EXCEPTION_ERROR_READING_TEXT_FILE", 31);
define("EXCEPTION_INVALID_RECORD_TYPE", 32);
define("EXCEPTION_NO_RECORDS_SELECTED", 33);
define("EXCEPTION_USELESS_OPERATION", 34);
define("EXCEPTION_NO_SUCH_COLOR", 35);
define("EXCEPTION_RESTART_FAIL", 36);
define("EXCEPTION_UNABLE_TO_COMMIT_CONFIG", 37);
define("EXCEPTION_FAIL_FILE_PUT_CONTENTS", 38);
define("EXCEPTION_CANNOT_READ_ARGS", 39);
define("EXCEPTION_COMMAND_ALREADY_REGISTERED", 40);
define("EXCEPTION_ATTEMPT_TO_REDEFINE_OPTION", 41);
define("EXCEPTION_MUST_BE_LAST_ARGUMENT", 42);
define("EXCEPTION_COMMAND_NOT_REGISTERED", 43);
define("EXCEPTION_CONSTRAINT_IS_NOT_ALLOWED", 44);
define("EXCEPTION_NAME_IS_NOT_ALLOWED", 45);
define("EXCEPTION_DEFAULT_NOT_ALLOWED", 46);
define("EXCEPTION_WRONG_OPTION_SPEC", 47);
define("EXCEPTION_OPTIONAL_ARGUMENT_EXCEPCTED", 48);
define("EXCEPTION_WRONG_ARGUMENT_SPEC", 49);
define("EXCEPTION_MISSING_VALUE", 50);
define("EXCEPTION_CANNOT_BE_COMBINED", 51);
define("EXCEPTION_AMBIGUOUS_OPTION", 52);
define("EXCEPTION_NOT_AN_INTEGER", 53);
define("EXCEPTION_NOT_A_FILE", 54);
define("EXCEPTION_NOT_A_DIRECTORY", 55);
define("EXCEPTION_NOT_A_BOOLEAN", 56);
define("EXCEPTION_NOT_VALID", 57);
define("EXCEPTION_UNKNOWN_OPTION", 58);
define("EXCEPTION_SUPERFLUOUS_ARGUMENT", 59);
define("EXCEPTION_MISSING_REQUIRED_OPTION", 60);
define("EXCEPTION_MISSING_REQUIRED_ARGUMENT", 61);
define("EXCEPTION_COLUMN_SIZES_MUST_BE_SPECIFIED", 62);
define("EXCEPTION_ONLY_ONE_FLUID_COLUMN_ALLOWED", 63);
define("EXCEPTION_UNKNOWN_COLUMN_FORMAT", 64);
define("EXCEPTION_CANNOT_FIT", 65);
define("EXCEPTION_EXIT", 66);
define("EXCEPTION_MUST_BE_A_STRING", 67);
define("EXCEPTION_INVALID_RULESET", 68);
define("EXCEPTION_NO_SNIFF_CLASS", 69);
define("EXCEPTION_SNIFF_DOES_NOT_EXIST", 70);
define("EXCEPTION_CLASS_NOT_FOUND", 71);
define("EXCEPTION_SNIFF_REGISTRATION_SHOULD_PROVIDE_ARRAY", 72);
define("EXCEPTION_NO_SOURCE_FILE", 73);
define("EXCEPTION_CONFIG_IS_NOT_WRITEABLE", 74);
define("EXCEPTION_UNREADABLE_FILE", 75);
define("EXCEPTION_CANNOT_DETECT_LINE_ENDINGS", 76);
define("EXCEPTION_MINIFIED_FILE_ENCOUNTERED", 77);
define("EXCEPTION_MAXIMUM_NESTING_LEVEL_REACHED", 78);
define("EXCEPTION_TOKEN_TYPE_IS_INCORRECT", 79);
define("EXCEPTION_TOKEN_TYPE_IS_NOT_T_FUNCTION", 80);
define("EXCEPTION_STACKPTR_MUST_BE_T_FUNCTION", 81);
define("EXCEPTION_STACKPTR_MUST_BE_T_VARIABLE", 82);
define("EXCEPTION_STACKPTR_IS_NOT_CLASS_MEMBER_VAR", 83);
define("EXCEPTION_STACKPTR_MUST_BE_T_CLASS", 84);
define("EXCEPTION_REPORT_TYPE_NOT_FOUND", 85);
define("EXCEPTION_CLASS_DOES_NOT_IMPLEMENT_REPORTING_INTERFACE", 86);
define("EXCEPTION_NO_TOKEN_TO_LISTEN_FOR", 87);
define("EXCEPTION_WRONG_PATTERN", 88);
define("EXCEPTION_PATTERN_NOT_FOR_THIS_CODE", 89);
define("EXCEPTION_SCOPE_TOKENS_LIST_IS_EMPTY", 90);
define("EXCEPTION_TOKENS_LIST_IS_EMPTY", 91);
define("EXCEPTION_INVALID_SCOPE_TOKENS", 92);
define("EXCEPTION_TAB_WIDTH_CANNOT_BE_ZERO", 93);
define("EXCEPTION_CANNOT_OPEN_FILE", 94);
define("EXCEPTION_JAVASCRIPTLINT_INVOCATION_FAILURE", 95);
define("EXCEPTION_ZENDCODEANALYZER_INVOCATION_FAILURE", 96);
define("EXCEPTION_UNEXPECTED_FILENAME", 97);
define("EXCEPTION_GETERRORLIST_MUST_RETURN_ARRAY", 98);
define("EXCEPTION_GETWARNINGLIST_MUST_RETURN_ARRAY", 99);
define("EXCEPTION_AMBIGUOUS_TYPE_DEFINITION", 100);
define("EXCEPTION_AMBIGUOUS_DEFAULT_DEFINITION", 101);
define("EXCEPTION_AMBIGUOUS_COMMENT_DEFINITION", 102);
define("EXCEPTION_UNRECOGNIZED_PARAMETERS", 103);
define("EXCEPTION_ALREADY_USED", 104);
define("EXCEPTION_NO_SUCH_SCHEMA", 105);
define("EXCEPTION_CANNOT_VALIDATE", 106);
define("EXCEPTION_NO_SUCH_FORM", 107);
define("EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS", 108);
define("EXCEPTION_UNKNOWN_SQL_DRIVER", 109);
define("EXCEPTION_NO_MYSQL_CONNECTION_DETAILS", 110);
define("EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS", 111);
define("EXCEPTION_CANNOT_SAVE_FILE", 112);
define("EXCEPTION_UNABLE_TO_COMMIT", 113);
define("EXCEPTION_INVALID_SCHEMA", 114);
define("EXCEPTION_XML_PARSING_ERROR", 115);
define("EXCEPTION_UNABLE_TO_EXPAND", 116);
define("EXCEPTION_ROOT_INDEX_NOT_VALID", 117);
define("EXCEPTION_UNUSED_ITEMS", 118);
define("EXCEPTION_INVALID_DOCUMENT", 119);
define("EXCEPTION_UNABLE_TO_LOAD_SCHEMA", 120);
define("EXCEPTION_UNABLE_TO_RETRIEVE", 121);
define("EXCEPTION_UNABLE_TO_GET_EXTERNAL", 122);
define("EXCEPTION_NAME_SHOULD_BE_SPECIFIED", 123);
define("EXCEPTION_TYPE_SHOULD_BE_SPECIFIED", 124);
define("EXCEPTION_INVALID_NAMETRACE", 125);
define("EXCEPTION_UNABLE_TO_RETURN", 126);
define("EXCEPTION_NO_ELEMENT_OF_TYPE", 127);
define("EXCEPTION_LOAD_XML_FAILED", 128);
define("EXCEPTION_UNKNOWN_DOCUMENT_TYPE", 129);
define("EXCEPTION_UNKNOWN_PATH", 130);
define("EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE", 131);
define("EXCEPTION_NO_TRANSLATION_METHOD", 132);
define("EXCEPTION_TRANSLATION_FAULT", 133);
define("EXCEPTION_WRONG_DISCOVERY_MODE", 134);
define("EXCEPTION_NO_FLATTENED_ARRAY", 135);

?>
