<?php

/**
 * PHP version 5.6.
 *
 * @author    Config Generator <mega@dev.logics.net.au>
 * @copyright 2013-2016 Vladimir Bashkirtsev
 * @license   https://opensource.org/licenses/MIT MIT License
 *
 * @version   SVN: $Date$ $Revision$
 *
 * @link      $HeadURL$
 */

/**
 * Automatically generated file, do not modify.
 *
 * @donottranslate
 */
(defined('GENGO_EXCEPTION_NO_API_KEY') === true) ?: define('GENGO_EXCEPTION_NO_API_KEY', 1);
(defined('GENGO_EXCEPTION_NO_PRIVATE_KEY') === true) ?: define('GENGO_EXCEPTION_NO_PRIVATE_KEY', 2);
(defined('GENGO_EXCEPTION_NO_RESPONSE_AVAILABLE_YET') === true) ?: define('GENGO_EXCEPTION_NO_RESPONSE_AVAILABLE_YET', 3);
(defined('GENGO_EXCEPTION_ID_IS_NOT_SET') === true) ?: define('GENGO_EXCEPTION_ID_IS_NOT_SET', 4);
(defined('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_RATING') === true) ?: define('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_RATING', 5);
(defined('GENGO_EXCEPTION_JOB_MUST_CONTAIN_VALID_REASON') === true) ?: define('GENGO_EXCEPTION_JOB_MUST_CONTAIN_VALID_REASON', 6);
(defined('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_FOLLOWUP') === true) ?: define('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_FOLLOWUP', 7);
(defined('GENGO_EXCEPTION_REASON_REQUIRED') === true) ?: define('GENGO_EXCEPTION_REASON_REQUIRED', 8);
(defined('GENGO_EXCEPTION_INVALID_RESPONSE_FORMAT') === true) ?: define('GENGO_EXCEPTION_INVALID_RESPONSE_FORMAT', 9);
(defined('GENGO_EXCEPTION_INVALID_API_KEY') === true) ?: define('GENGO_EXCEPTION_INVALID_API_KEY', 10);
(defined('GENGO_EXCEPTION_INVALID_PRIVATE_KEY') === true) ?: define('GENGO_EXCEPTION_INVALID_PRIVATE_KEY', 11);
(defined('GENGO_EXCEPTION_INVALID_JOB_ID') === true) ?: define('GENGO_EXCEPTION_INVALID_JOB_ID', 12);
(defined('GENGO_EXCEPTION_INVALID_REVISION_ID') === true) ?: define('GENGO_EXCEPTION_INVALID_REVISION_ID', 13);
(defined('GENGO_EXCEPTION_COMMENT_REQUIRED') === true) ?: define('GENGO_EXCEPTION_COMMENT_REQUIRED', 14);
(defined('GENGO_EXCEPTION_VALID_PARAMETER_IS_REQUIRED') === true) ?: define('GENGO_EXCEPTION_VALID_PARAMETER_IS_REQUIRED', 15);
(defined('GENGO_EXCEPTION_URL_ATTACHMENTS_NOT_ARRAY') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENTS_NOT_ARRAY', 16);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_IS_NOT_HTTP_URL') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_IS_NOT_HTTP_URL', 17);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_FILENAME') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_FILENAME', 18);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_MIMETYPE') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_MIMETYPE', 19);
(defined('GENGO_EXCEPTION_MUST_CONTAIN_VALID_STATUS') === true) ?: define('GENGO_EXCEPTION_MUST_CONTAIN_VALID_STATUS', 20);
(defined('GENGO_EXCEPTION_TIMESTAMP_MUST_BE_VALID') === true) ?: define('GENGO_EXCEPTION_TIMESTAMP_MUST_BE_VALID', 21);
(defined('GENGO_EXCEPTION_COUNT_MUST_MUST_BE_VALID') === true) ?: define('GENGO_EXCEPTION_COUNT_MUST_MUST_BE_VALID', 22);
(defined('GENGO_EXCEPTION_JOB_ID_REQUIRED') === true) ?: define('GENGO_EXCEPTION_JOB_ID_REQUIRED', 23);
(defined('GENGO_EXCEPTION_INVALID_JOB_ID_SUPPLIED') === true) ?: define('GENGO_EXCEPTION_INVALID_JOB_ID_SUPPLIED', 24);
(defined('GENGO_EXCEPTION_MUST_CONTAIN_VALID_BODY') === true) ?: define('GENGO_EXCEPTION_MUST_CONTAIN_VALID_BODY', 25);
(defined('GENGO_EXCEPTION_JOB_MISSING_FILE_KEY') === true) ?: define('GENGO_EXCEPTION_JOB_MISSING_FILE_KEY', 26);
(defined('GENGO_EXCEPTION_IS_NOT_VALID_FILE_KEY') === true) ?: define('GENGO_EXCEPTION_IS_NOT_VALID_FILE_KEY', 27);
(defined('GENGO_EXCEPTION_FILE_KEY_MISSING') === true) ?: define('GENGO_EXCEPTION_FILE_KEY_MISSING', 28);
(defined('GENGO_EXCEPTION_COULD_NOT_FIND_FILE') === true) ?: define('GENGO_EXCEPTION_COULD_NOT_FIND_FILE', 29);
(defined('EXCEPTION_CANNOT_RUN_TESSERACT') === true) ?: define('EXCEPTION_CANNOT_RUN_TESSERACT', 30);
(defined('EXCEPTION_ERROR_READING_TEXT_FILE') === true) ?: define('EXCEPTION_ERROR_READING_TEXT_FILE', 31);
(defined('EXCEPTION_INVALID_RECORD_TYPE') === true) ?: define('EXCEPTION_INVALID_RECORD_TYPE', 32);
(defined('EXCEPTION_NO_RECORDS_SELECTED') === true) ?: define('EXCEPTION_NO_RECORDS_SELECTED', 33);
(defined('EXCEPTION_USELESS_OPERATION') === true) ?: define('EXCEPTION_USELESS_OPERATION', 34);
(defined('EXCEPTION_NO_SUCH_COLOR') === true) ?: define('EXCEPTION_NO_SUCH_COLOR', 35);
(defined('EXCEPTION_RESTART_FAIL') === true) ?: define('EXCEPTION_RESTART_FAIL', 36);
(defined('EXCEPTION_UNABLE_TO_COMMIT_CONFIG') === true) ?: define('EXCEPTION_UNABLE_TO_COMMIT_CONFIG', 37);
(defined('EXCEPTION_FAIL_FILE_PUT_CONTENTS') === true) ?: define('EXCEPTION_FAIL_FILE_PUT_CONTENTS', 38);
(defined('EXCEPTION_CANNOT_READ_ARGS') === true) ?: define('EXCEPTION_CANNOT_READ_ARGS', 39);
(defined('EXCEPTION_COMMAND_ALREADY_REGISTERED') === true) ?: define('EXCEPTION_COMMAND_ALREADY_REGISTERED', 40);
(defined('EXCEPTION_ATTEMPT_TO_REDEFINE_OPTION') === true) ?: define('EXCEPTION_ATTEMPT_TO_REDEFINE_OPTION', 41);
(defined('EXCEPTION_MUST_BE_LAST_ARGUMENT') === true) ?: define('EXCEPTION_MUST_BE_LAST_ARGUMENT', 42);
(defined('EXCEPTION_COMMAND_NOT_REGISTERED') === true) ?: define('EXCEPTION_COMMAND_NOT_REGISTERED', 43);
(defined('EXCEPTION_CONSTRAINT_IS_NOT_ALLOWED') === true) ?: define('EXCEPTION_CONSTRAINT_IS_NOT_ALLOWED', 44);
(defined('EXCEPTION_NAME_IS_NOT_ALLOWED') === true) ?: define('EXCEPTION_NAME_IS_NOT_ALLOWED', 45);
(defined('EXCEPTION_DEFAULT_NOT_ALLOWED') === true) ?: define('EXCEPTION_DEFAULT_NOT_ALLOWED', 46);
(defined('EXCEPTION_WRONG_OPTION_SPEC') === true) ?: define('EXCEPTION_WRONG_OPTION_SPEC', 47);
(defined('EXCEPTION_OPTIONAL_ARGUMENT_EXCEPCTED') === true) ?: define('EXCEPTION_OPTIONAL_ARGUMENT_EXCEPCTED', 48);
(defined('EXCEPTION_WRONG_ARGUMENT_SPEC') === true) ?: define('EXCEPTION_WRONG_ARGUMENT_SPEC', 49);
(defined('EXCEPTION_MISSING_VALUE') === true) ?: define('EXCEPTION_MISSING_VALUE', 50);
(defined('EXCEPTION_CANNOT_BE_COMBINED') === true) ?: define('EXCEPTION_CANNOT_BE_COMBINED', 51);
(defined('EXCEPTION_AMBIGUOUS_OPTION') === true) ?: define('EXCEPTION_AMBIGUOUS_OPTION', 52);
(defined('EXCEPTION_NOT_AN_INTEGER') === true) ?: define('EXCEPTION_NOT_AN_INTEGER', 53);
(defined('EXCEPTION_NOT_A_FILE') === true) ?: define('EXCEPTION_NOT_A_FILE', 54);
(defined('EXCEPTION_NOT_A_DIRECTORY') === true) ?: define('EXCEPTION_NOT_A_DIRECTORY', 55);
(defined('EXCEPTION_NOT_A_BOOLEAN') === true) ?: define('EXCEPTION_NOT_A_BOOLEAN', 56);
(defined('EXCEPTION_NOT_VALID') === true) ?: define('EXCEPTION_NOT_VALID', 57);
(defined('EXCEPTION_UNKNOWN_OPTION') === true) ?: define('EXCEPTION_UNKNOWN_OPTION', 58);
(defined('EXCEPTION_SUPERFLUOUS_ARGUMENT') === true) ?: define('EXCEPTION_SUPERFLUOUS_ARGUMENT', 59);
(defined('EXCEPTION_MISSING_REQUIRED_OPTION') === true) ?: define('EXCEPTION_MISSING_REQUIRED_OPTION', 60);
(defined('EXCEPTION_MISSING_REQUIRED_ARGUMENT') === true) ?: define('EXCEPTION_MISSING_REQUIRED_ARGUMENT', 61);
(defined('EXCEPTION_COLUMN_SIZES_MUST_BE_SPECIFIED') === true) ?: define('EXCEPTION_COLUMN_SIZES_MUST_BE_SPECIFIED', 62);
(defined('EXCEPTION_ONLY_ONE_FLUID_COLUMN_ALLOWED') === true) ?: define('EXCEPTION_ONLY_ONE_FLUID_COLUMN_ALLOWED', 63);
(defined('EXCEPTION_UNKNOWN_COLUMN_FORMAT') === true) ?: define('EXCEPTION_UNKNOWN_COLUMN_FORMAT', 64);
(defined('EXCEPTION_CANNOT_FIT') === true) ?: define('EXCEPTION_CANNOT_FIT', 65);
(defined('EXCEPTION_EXIT') === true) ?: define('EXCEPTION_EXIT', 66);
(defined('EXCEPTION_MUST_BE_A_STRING') === true) ?: define('EXCEPTION_MUST_BE_A_STRING', 67);
(defined('EXCEPTION_INVALID_RULESET') === true) ?: define('EXCEPTION_INVALID_RULESET', 68);
(defined('EXCEPTION_NO_SNIFF_CLASS') === true) ?: define('EXCEPTION_NO_SNIFF_CLASS', 69);
(defined('EXCEPTION_SNIFF_DOES_NOT_EXIST') === true) ?: define('EXCEPTION_SNIFF_DOES_NOT_EXIST', 70);
(defined('EXCEPTION_CLASS_NOT_FOUND') === true) ?: define('EXCEPTION_CLASS_NOT_FOUND', 71);
(defined('EXCEPTION_SNIFF_REGISTRATION_SHOULD_PROVIDE_ARRAY') === true) ?: define('EXCEPTION_SNIFF_REGISTRATION_SHOULD_PROVIDE_ARRAY', 72);
(defined('EXCEPTION_NO_SOURCE_FILE') === true) ?: define('EXCEPTION_NO_SOURCE_FILE', 73);
(defined('EXCEPTION_CONFIG_IS_NOT_WRITEABLE') === true) ?: define('EXCEPTION_CONFIG_IS_NOT_WRITEABLE', 74);
(defined('EXCEPTION_UNREADABLE_FILE') === true) ?: define('EXCEPTION_UNREADABLE_FILE', 75);
(defined('EXCEPTION_CANNOT_DETECT_LINE_ENDINGS') === true) ?: define('EXCEPTION_CANNOT_DETECT_LINE_ENDINGS', 76);
(defined('EXCEPTION_MINIFIED_FILE_ENCOUNTERED') === true) ?: define('EXCEPTION_MINIFIED_FILE_ENCOUNTERED', 77);
(defined('EXCEPTION_MAXIMUM_NESTING_LEVEL_REACHED') === true) ?: define('EXCEPTION_MAXIMUM_NESTING_LEVEL_REACHED', 78);
(defined('EXCEPTION_TOKEN_TYPE_IS_INCORRECT') === true) ?: define('EXCEPTION_TOKEN_TYPE_IS_INCORRECT', 79);
(defined('EXCEPTION_TOKEN_TYPE_IS_NOT_T_FUNCTION') === true) ?: define('EXCEPTION_TOKEN_TYPE_IS_NOT_T_FUNCTION', 80);
(defined('EXCEPTION_STACKPTR_MUST_BE_T_FUNCTION') === true) ?: define('EXCEPTION_STACKPTR_MUST_BE_T_FUNCTION', 81);
(defined('EXCEPTION_STACKPTR_MUST_BE_T_VARIABLE') === true) ?: define('EXCEPTION_STACKPTR_MUST_BE_T_VARIABLE', 82);
(defined('EXCEPTION_STACKPTR_IS_NOT_CLASS_MEMBER_VAR') === true) ?: define('EXCEPTION_STACKPTR_IS_NOT_CLASS_MEMBER_VAR', 83);
(defined('EXCEPTION_STACKPTR_MUST_BE_T_CLASS') === true) ?: define('EXCEPTION_STACKPTR_MUST_BE_T_CLASS', 84);
(defined('EXCEPTION_REPORT_TYPE_NOT_FOUND') === true) ?: define('EXCEPTION_REPORT_TYPE_NOT_FOUND', 85);
(defined('EXCEPTION_CLASS_DOES_NOT_IMPLEMENT_REPORTING_INTERFACE') === true) ?: define('EXCEPTION_CLASS_DOES_NOT_IMPLEMENT_REPORTING_INTERFACE', 86);
(defined('EXCEPTION_NO_TOKEN_TO_LISTEN_FOR') === true) ?: define('EXCEPTION_NO_TOKEN_TO_LISTEN_FOR', 87);
(defined('EXCEPTION_WRONG_PATTERN') === true) ?: define('EXCEPTION_WRONG_PATTERN', 88);
(defined('EXCEPTION_PATTERN_NOT_FOR_THIS_CODE') === true) ?: define('EXCEPTION_PATTERN_NOT_FOR_THIS_CODE', 89);
(defined('EXCEPTION_SCOPE_TOKENS_LIST_IS_EMPTY') === true) ?: define('EXCEPTION_SCOPE_TOKENS_LIST_IS_EMPTY', 90);
(defined('EXCEPTION_TOKENS_LIST_IS_EMPTY') === true) ?: define('EXCEPTION_TOKENS_LIST_IS_EMPTY', 91);
(defined('EXCEPTION_INVALID_SCOPE_TOKENS') === true) ?: define('EXCEPTION_INVALID_SCOPE_TOKENS', 92);
(defined('EXCEPTION_TAB_WIDTH_CANNOT_BE_ZERO') === true) ?: define('EXCEPTION_TAB_WIDTH_CANNOT_BE_ZERO', 93);
(defined('EXCEPTION_CANNOT_OPEN_FILE') === true) ?: define('EXCEPTION_CANNOT_OPEN_FILE', 94);
(defined('EXCEPTION_JAVASCRIPTLINT_INVOCATION_FAILURE') === true) ?: define('EXCEPTION_JAVASCRIPTLINT_INVOCATION_FAILURE', 95);
(defined('EXCEPTION_ZENDCODEANALYZER_INVOCATION_FAILURE') === true) ?: define('EXCEPTION_ZENDCODEANALYZER_INVOCATION_FAILURE', 96);
(defined('EXCEPTION_UNEXPECTED_FILENAME') === true) ?: define('EXCEPTION_UNEXPECTED_FILENAME', 97);
(defined('EXCEPTION_GETERRORLIST_MUST_RETURN_ARRAY') === true) ?: define('EXCEPTION_GETERRORLIST_MUST_RETURN_ARRAY', 98);
(defined('EXCEPTION_GETWARNINGLIST_MUST_RETURN_ARRAY') === true) ?: define('EXCEPTION_GETWARNINGLIST_MUST_RETURN_ARRAY', 99);
(defined('EXCEPTION_AMBIGUOUS_TYPE_DEFINITION') === true) ?: define('EXCEPTION_AMBIGUOUS_TYPE_DEFINITION', 100);
(defined('EXCEPTION_AMBIGUOUS_DEFAULT_DEFINITION') === true) ?: define('EXCEPTION_AMBIGUOUS_DEFAULT_DEFINITION', 101);
(defined('EXCEPTION_AMBIGUOUS_COMMENT_DEFINITION') === true) ?: define('EXCEPTION_AMBIGUOUS_COMMENT_DEFINITION', 102);
(defined('EXCEPTION_UNRECOGNIZED_PARAMETERS') === true) ?: define('EXCEPTION_UNRECOGNIZED_PARAMETERS', 103);
(defined('EXCEPTION_ALREADY_USED') === true) ?: define('EXCEPTION_ALREADY_USED', 104);
(defined('EXCEPTION_INVALID_COMPOSER_JSON') === true) ?: define('EXCEPTION_INVALID_COMPOSER_JSON', 105);
(defined('EXCEPTION_CANNOT_FIND_COMPOSER_JSON') === true) ?: define('EXCEPTION_CANNOT_FIND_COMPOSER_JSON', 106);
(defined('EXCEPTION_NO_SUCH_SCHEMA') === true) ?: define('EXCEPTION_NO_SUCH_SCHEMA', 107);
(defined('EXCEPTION_CANNOT_VALIDATE') === true) ?: define('EXCEPTION_CANNOT_VALIDATE', 108);
(defined('EXCEPTION_NO_SUCH_FORM') === true) ?: define('EXCEPTION_NO_SUCH_FORM', 109);
(defined('EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS') === true) ?: define('EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS', 110);
(defined('EXCEPTION_UNKNOWN_SQL_DRIVER') === true) ?: define('EXCEPTION_UNKNOWN_SQL_DRIVER', 111);
(defined('EXCEPTION_NO_MYSQL_CONNECTION_DETAILS') === true) ?: define('EXCEPTION_NO_MYSQL_CONNECTION_DETAILS', 112);
(defined('EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS') === true) ?: define('EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS', 113);
(defined('EXCEPTION_CANNOT_SAVE_FILE') === true) ?: define('EXCEPTION_CANNOT_SAVE_FILE', 114);
(defined('EXCEPTION_UNABLE_TO_COMMIT') === true) ?: define('EXCEPTION_UNABLE_TO_COMMIT', 115);
(defined('EXCEPTION_INVALID_SCHEMA') === true) ?: define('EXCEPTION_INVALID_SCHEMA', 116);
(defined('EXCEPTION_XML_PARSING_ERROR') === true) ?: define('EXCEPTION_XML_PARSING_ERROR', 117);
(defined('EXCEPTION_UNABLE_TO_EXPAND') === true) ?: define('EXCEPTION_UNABLE_TO_EXPAND', 118);
(defined('EXCEPTION_ROOT_INDEX_NOT_VALID') === true) ?: define('EXCEPTION_ROOT_INDEX_NOT_VALID', 119);
(defined('EXCEPTION_UNUSED_ITEMS') === true) ?: define('EXCEPTION_UNUSED_ITEMS', 120);
(defined('EXCEPTION_INVALID_DOCUMENT') === true) ?: define('EXCEPTION_INVALID_DOCUMENT', 121);
(defined('EXCEPTION_UNABLE_TO_LOAD_SCHEMA') === true) ?: define('EXCEPTION_UNABLE_TO_LOAD_SCHEMA', 122);
(defined('EXCEPTION_UNABLE_TO_RETRIEVE') === true) ?: define('EXCEPTION_UNABLE_TO_RETRIEVE', 123);
(defined('EXCEPTION_UNABLE_TO_GET_EXTERNAL') === true) ?: define('EXCEPTION_UNABLE_TO_GET_EXTERNAL', 124);
(defined('EXCEPTION_NAME_SHOULD_BE_SPECIFIED') === true) ?: define('EXCEPTION_NAME_SHOULD_BE_SPECIFIED', 125);
(defined('EXCEPTION_TYPE_SHOULD_BE_SPECIFIED') === true) ?: define('EXCEPTION_TYPE_SHOULD_BE_SPECIFIED', 126);
(defined('EXCEPTION_INVALID_NAMETRACE') === true) ?: define('EXCEPTION_INVALID_NAMETRACE', 127);
(defined('EXCEPTION_UNABLE_TO_RETURN') === true) ?: define('EXCEPTION_UNABLE_TO_RETURN', 128);
(defined('EXCEPTION_NO_ELEMENT_OF_TYPE') === true) ?: define('EXCEPTION_NO_ELEMENT_OF_TYPE', 129);
(defined('EXCEPTION_LOAD_XML_FAILED') === true) ?: define('EXCEPTION_LOAD_XML_FAILED', 130);
(defined('EXCEPTION_UNKNOWN_DOCUMENT_TYPE') === true) ?: define('EXCEPTION_UNKNOWN_DOCUMENT_TYPE', 131);
(defined('EXCEPTION_UNKNOWN_PATH') === true) ?: define('EXCEPTION_UNKNOWN_PATH', 132);
(defined('EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE') === true) ?: define('EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE', 133);
(defined('EXCEPTION_NO_TRANSLATION_METHOD') === true) ?: define('EXCEPTION_NO_TRANSLATION_METHOD', 134);
(defined('EXCEPTION_TRANSLATION_FAULT') === true) ?: define('EXCEPTION_TRANSLATION_FAULT', 135);
(defined('EXCEPTION_WRONG_DISCOVERY_MODE') === true) ?: define('EXCEPTION_WRONG_DISCOVERY_MODE', 136);
(defined('EXCEPTION_NO_FLATTENED_ARRAY') === true) ?: define('EXCEPTION_NO_FLATTENED_ARRAY', 137);
