<?php

/**
 * PHP version 5.6.
 *
 * @package   Manifest
 *
 * @author    Config Generator <mega@dev.logics.net.au>
 * @copyright 2013-2016 Vladimir Bashkirtsev
 * @license   https://opensource.org/licenses/MIT MIT License
 *
 * @version   SVN: $Date$ $Revision$
 *
 * @link      $HeadURL$
 */

/**
 * Automatically generated file, do not modify.
 *
 * @donottranslate
 */
(defined('GENGO_EXCEPTION_NO_API_KEY') === true) ?: define('GENGO_EXCEPTION_NO_API_KEY', 1);
(defined('GENGO_EXCEPTION_NO_PRIVATE_KEY') === true) ?: define('GENGO_EXCEPTION_NO_PRIVATE_KEY', 2);
(defined('GENGO_EXCEPTION_NO_RESPONSE_AVAILABLE_YET') === true) ?: define('GENGO_EXCEPTION_NO_RESPONSE_AVAILABLE_YET', 3);
(defined('GENGO_EXCEPTION_ID_IS_NOT_SET') === true) ?: define('GENGO_EXCEPTION_ID_IS_NOT_SET', 4);
(defined('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_RATING') === true) ?: define('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_RATING', 5);
(defined('GENGO_EXCEPTION_JOB_MUST_CONTAIN_VALID_REASON') === true) ?: define('GENGO_EXCEPTION_JOB_MUST_CONTAIN_VALID_REASON', 6);
(defined('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_FOLLOWUP') === true) ?: define('GENGO_EXCEPTION_JOB_SHOULD_CONTAIN_VALID_FOLLOWUP', 7);
(defined('GENGO_EXCEPTION_REASON_REQUIRED') === true) ?: define('GENGO_EXCEPTION_REASON_REQUIRED', 8);
(defined('GENGO_EXCEPTION_INVALID_RESPONSE_FORMAT') === true) ?: define('GENGO_EXCEPTION_INVALID_RESPONSE_FORMAT', 9);
(defined('GENGO_EXCEPTION_INVALID_API_KEY') === true) ?: define('GENGO_EXCEPTION_INVALID_API_KEY', 10);
(defined('GENGO_EXCEPTION_INVALID_PRIVATE_KEY') === true) ?: define('GENGO_EXCEPTION_INVALID_PRIVATE_KEY', 11);
(defined('GENGO_EXCEPTION_INVALID_JOB_ID') === true) ?: define('GENGO_EXCEPTION_INVALID_JOB_ID', 12);
(defined('GENGO_EXCEPTION_INVALID_REVISION_ID') === true) ?: define('GENGO_EXCEPTION_INVALID_REVISION_ID', 13);
(defined('GENGO_EXCEPTION_COMMENT_REQUIRED') === true) ?: define('GENGO_EXCEPTION_COMMENT_REQUIRED', 14);
(defined('GENGO_EXCEPTION_VALID_PARAMETER_IS_REQUIRED') === true) ?: define('GENGO_EXCEPTION_VALID_PARAMETER_IS_REQUIRED', 15);
(defined('GENGO_EXCEPTION_URL_ATTACHMENTS_NOT_ARRAY') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENTS_NOT_ARRAY', 16);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_IS_NOT_HTTP_URL') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_IS_NOT_HTTP_URL', 17);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_FILENAME') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_FILENAME', 18);
(defined('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_MIMETYPE') === true) ?: define('GENGO_EXCEPTION_URL_ATTACHMENT_NEEDS_MIMETYPE', 19);
(defined('GENGO_EXCEPTION_MUST_CONTAIN_VALID_STATUS') === true) ?: define('GENGO_EXCEPTION_MUST_CONTAIN_VALID_STATUS', 20);
(defined('GENGO_EXCEPTION_TIMESTAMP_MUST_BE_VALID') === true) ?: define('GENGO_EXCEPTION_TIMESTAMP_MUST_BE_VALID', 21);
(defined('GENGO_EXCEPTION_COUNT_MUST_MUST_BE_VALID') === true) ?: define('GENGO_EXCEPTION_COUNT_MUST_MUST_BE_VALID', 22);
(defined('GENGO_EXCEPTION_JOB_ID_REQUIRED') === true) ?: define('GENGO_EXCEPTION_JOB_ID_REQUIRED', 23);
(defined('GENGO_EXCEPTION_INVALID_JOB_ID_SUPPLIED') === true) ?: define('GENGO_EXCEPTION_INVALID_JOB_ID_SUPPLIED', 24);
(defined('GENGO_EXCEPTION_MUST_CONTAIN_VALID_BODY') === true) ?: define('GENGO_EXCEPTION_MUST_CONTAIN_VALID_BODY', 25);
(defined('GENGO_EXCEPTION_JOB_MISSING_FILE_KEY') === true) ?: define('GENGO_EXCEPTION_JOB_MISSING_FILE_KEY', 26);
(defined('GENGO_EXCEPTION_IS_NOT_VALID_FILE_KEY') === true) ?: define('GENGO_EXCEPTION_IS_NOT_VALID_FILE_KEY', 27);
(defined('GENGO_EXCEPTION_FILE_KEY_MISSING') === true) ?: define('GENGO_EXCEPTION_FILE_KEY_MISSING', 28);
(defined('GENGO_EXCEPTION_COULD_NOT_FIND_FILE') === true) ?: define('GENGO_EXCEPTION_COULD_NOT_FIND_FILE', 29);
(defined('EXCEPTION_CANNOT_RUN_TESSERACT') === true) ?: define('EXCEPTION_CANNOT_RUN_TESSERACT', 30);
(defined('EXCEPTION_ERROR_READING_TEXT_FILE') === true) ?: define('EXCEPTION_ERROR_READING_TEXT_FILE', 31);
(defined('EXCEPTION_INVALID_RECORD_TYPE') === true) ?: define('EXCEPTION_INVALID_RECORD_TYPE', 32);
(defined('EXCEPTION_NO_RECORDS_SELECTED') === true) ?: define('EXCEPTION_NO_RECORDS_SELECTED', 33);
(defined('EXCEPTION_USELESS_OPERATION') === true) ?: define('EXCEPTION_USELESS_OPERATION', 34);
(defined('EXCEPTION_NO_SUCH_SCHEMA') === true) ?: define('EXCEPTION_NO_SUCH_SCHEMA', 35);
(defined('EXCEPTION_CANNOT_VALIDATE') === true) ?: define('EXCEPTION_CANNOT_VALIDATE', 36);
(defined('EXCEPTION_NO_SUCH_FORM') === true) ?: define('EXCEPTION_NO_SUCH_FORM', 37);
(defined('EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS') === true) ?: define('EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS', 38);
(defined('EXCEPTION_UNKNOWN_SQL_DRIVER') === true) ?: define('EXCEPTION_UNKNOWN_SQL_DRIVER', 39);
(defined('EXCEPTION_NO_MYSQL_CONNECTION_DETAILS') === true) ?: define('EXCEPTION_NO_MYSQL_CONNECTION_DETAILS', 40);
(defined('EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS') === true) ?: define('EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS', 41);
(defined('EXCEPTION_INVALID_SCHEMA') === true) ?: define('EXCEPTION_INVALID_SCHEMA', 42);
(defined('EXCEPTION_XML_PARSING_ERROR') === true) ?: define('EXCEPTION_XML_PARSING_ERROR', 43);
(defined('EXCEPTION_UNABLE_TO_EXPAND') === true) ?: define('EXCEPTION_UNABLE_TO_EXPAND', 44);
(defined('EXCEPTION_ROOT_INDEX_NOT_VALID') === true) ?: define('EXCEPTION_ROOT_INDEX_NOT_VALID', 45);
(defined('EXCEPTION_UNUSED_ITEMS') === true) ?: define('EXCEPTION_UNUSED_ITEMS', 46);
(defined('EXCEPTION_INVALID_DOCUMENT') === true) ?: define('EXCEPTION_INVALID_DOCUMENT', 47);
(defined('EXCEPTION_UNABLE_TO_LOAD_SCHEMA') === true) ?: define('EXCEPTION_UNABLE_TO_LOAD_SCHEMA', 48);
(defined('EXCEPTION_UNABLE_TO_RETRIEVE') === true) ?: define('EXCEPTION_UNABLE_TO_RETRIEVE', 49);
(defined('EXCEPTION_UNABLE_TO_GET_EXTERNAL') === true) ?: define('EXCEPTION_UNABLE_TO_GET_EXTERNAL', 50);
(defined('EXCEPTION_NAME_SHOULD_BE_SPECIFIED') === true) ?: define('EXCEPTION_NAME_SHOULD_BE_SPECIFIED', 51);
(defined('EXCEPTION_TYPE_SHOULD_BE_SPECIFIED') === true) ?: define('EXCEPTION_TYPE_SHOULD_BE_SPECIFIED', 52);
(defined('EXCEPTION_INVALID_NAMETRACE') === true) ?: define('EXCEPTION_INVALID_NAMETRACE', 53);
(defined('EXCEPTION_UNABLE_TO_RETURN') === true) ?: define('EXCEPTION_UNABLE_TO_RETURN', 54);
(defined('EXCEPTION_NO_ELEMENT_OF_TYPE') === true) ?: define('EXCEPTION_NO_ELEMENT_OF_TYPE', 55);
(defined('EXCEPTION_LOAD_XML_FAILED') === true) ?: define('EXCEPTION_LOAD_XML_FAILED', 56);
(defined('EXCEPTION_UNKNOWN_DOCUMENT_TYPE') === true) ?: define('EXCEPTION_UNKNOWN_DOCUMENT_TYPE', 57);
(defined('EXCEPTION_UNKNOWN_PATH') === true) ?: define('EXCEPTION_UNKNOWN_PATH', 58);
(defined('EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE') === true) ?: define('EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE', 59);
(defined('EXCEPTION_NO_TRANSLATION_METHOD') === true) ?: define('EXCEPTION_NO_TRANSLATION_METHOD', 60);
(defined('EXCEPTION_TRANSLATION_FAULT') === true) ?: define('EXCEPTION_TRANSLATION_FAULT', 61);
(defined('EXCEPTION_WRONG_DISCOVERY_MODE') === true) ?: define('EXCEPTION_WRONG_DISCOVERY_MODE', 62);
(defined('EXCEPTION_NO_FLATTENED_ARRAY') === true) ?: define('EXCEPTION_NO_FLATTENED_ARRAY', 63);
